### ISSUE TITLE
makefile: fix install-target, was: "Missing man page"

### ISSUE THREAD

**Issue by DavidRabel-b1** [poinck/ocelot#15]
make install tries to install a man page, but it does not exist.

**Comment by DavidRabel-b1** [comment]
I just recognized, that make install does not install other binaries than ocelot. So maybe it's the makefile that has to be fixed. :)

**Comment by poinck** [comment]
Indeed, currently it only tries to compile the forked `monsterwm`. I did not look into the "install" target, because I want to have it compatible with the saved_config-useflag from Gentoo, like it works for other suckless-tools.

I am in the middle of a redesign of the side-panel, so in the meantime you or someone else can help here. (:
